TA#30212 commissions
Numigi/odoo-sale-addons pull request #125
Opened 2021-06-29 18:00 UTC by gabgosrob

2021-06-29 18:14 UTC, ddufresne requested changes

2021-06-29 18:14 UTC, ddufresne commented on commission/models/commission_target.py
> +            self.env["commission.target"].search(
Ici, les cibles doivent être filtrées par société. Comme dans _get_invoices.

2021-06-29 18:14 UTC, ddufresne commented on commission/models/commission_target.py
> +    def create(self, vals):
Il faut éviter de se baser sur une string arbitraire dans ce genre de logique.
Vaudrait mieux toujours définir la séquence dans le nom.

2021-06-29 18:14 UTC, ddufresne commented on commission/models/commission_target.py
> +        return result
```suggestion
        target = super(CommissionTarget, self).create(vals)
        target.name = target._get_next_sequence_number()
        return target
```

2021-06-29 18:14 UTC, ddufresne commented on commission/models/commission_target.py
> +        return result
Il y a différentes raisons pour cette façon de faire, mais entre autres, ceci permet d'éviter les trous dans la séquence.

``super().create(vals)`` peut tomber en erreur si une contrainte est levée.

Du moment que tu appelles ``self.env['ir.sequence'].next_by_code(...)`` le numéro de séquence est consommé et un rollback de la transaction n'y change rien.

2021-06-29 18:14 UTC, ddufresne commented on commission/models/commission_target.py
> +        return result
L'autre raison est de rendre _get_next_sequence_number est plus facile à tester que create.

Il faut aussi tester nottament le cas du multi-société:
```python
self.env['ir.sequence'].with_context(force_company=self.company_id).next_by_code(...)
```

Dans Odoo, on veut parfois des séquences distinctes pour chaque société.

2021-06-29 18:18 UTC, ddufresne commented on commission/views/target.xml
> +                    <field name="state" widget="statusbar" statebar_visible="draft,confirmed,done"/>
Ça serait bien de ramener les attributs des boutons sur différentes lignes. Comme ça, ça sera plus facile à réviser. Le "git blame" sera plus précis aussi.

2021-06-29 20:12 UTC, ddufresne requested changes

2021-06-29 20:12 UTC, ddufresne commented on commission/views/target.xml
> +                    <field name="state" widget="statusbar" statebar_visible="draft,confirmed,done"/>
Aussi, ramener les domaines à une seule condition lorsque possible.

2021-06-30 22:45 UTC, gabgosrob commented
Reste encore 5 tests à régler, certains en lien avec les changements de logique des taux (pourcentage versus entier) et d'autres avec les accès.

2021-07-06 19:12 UTC, merged