TA#30212 README update
Numigi/odoo-sale-addons pull request #128
Opened 2021-07-07 23:24 UTC by gabgosrob

2021-07-12 11:37 UTC, ddufresne requested changes
Il faudrait expliquer dans le README comment les filtres par tags fonctionnent.

2021-07-12 11:37 UTC, ddufresne commented on commission/models/commission_target.py
> +        tags = self.env["sale.order.line"].search(
Une opération search est très lente dans Odoo. Il vaut mieux utiliser la relation entre les deux lignes.

line.sale_line_id.order_id.so_tag_ids

2021-07-12 20:51 UTC, gabgosrob commented on commission/models/commission_target.py
> +        tags = self.env["sale.order.line"].search(
J'ai fait un search puisque la relation sale_line_id ne fonctionnait pas. Peut être que je l'ai mal écrit? Sinon je pourrais la créer moi même j'imagine?

2021-07-13 18:10 UTC, ddufresne requested changes

2021-07-13 18:10 UTC, ddufresne commented on .docker_files/main/__manifest__.py
> -        "commission_payroll_preparation",
@gabgosrob pourquoi enlever les deux modules?

2021-07-13 18:10 UTC, ddufresne commented on commission/README.rst
> +You cannot put a tag both as included and excluded.
@gabgosrob quand je demandais des explications sur le fonctionnement des tags, ce n'est pas à ce niveau de détails que je m'attendais.

Pour quelqu'un qui ne connait pas le contexte, ça ne me paraît pas évident.

Ça serait bien d'avoir un screenshot. Une image vaut milles mots.

Présentement, il faut aller lire le code d'un module en dépendance pour comprendre qu'il s'agit de tags définis sur le sale order associé à la ligne de facture.

2021-07-13 18:10 UTC, ddufresne commented on commission/models/commission_category.py
> +                    raise ValidationError("You cannot have a tag included and excluded at the same time.")
Cette contrainte ne sera pas utile.

2021-07-13 18:10 UTC, ddufresne commented on commission/models/commission_target.py
> +        tags = self.env["sale.order.line"].search(
@gabgosrob c'est sale_line_ids, il te manquait probablement le s

2021-07-13 18:10 UTC, ddufresne commented on commission/tests/test_commission_personal.py
> +            }
@gabgosrob il faudrait cleaner le test. Extraire la création d'un sale.order et d'une sale.order.line dans des méthodes séparées.

2021-07-13 18:10 UTC, ddufresne commented on commission/__manifest__.py
> +        "sale_stock",
Pourquoi sale_stock en dépendance?

Le module peut fonctionner selon moi sans la partie inventaire.

2021-07-13 19:06 UTC, gabgosrob commented on commission/__manifest__.py
> +        "sale_stock",
Il rajoute des champs qui font le lien entre les invoice et les sale order, donc ca me rend la tâche un peu plus facile pour les tags.

2021-07-14 20:36 UTC, ddufresne approved these changes

2021-07-14 20:36 UTC, merged