TA#47377 : Add sale Order available Qty popover alternative module
Numigi/odoo-sale-addons pull request #237
Opened 2022-11-14 13:44 UTC by abenzbiria

Il reste à ajouter les images Readme aprés la validation de bon focntionnement

2022-11-14 14:36 UTC, jjbreard2 commented
@majouda Hello Majda

Aurais tu qqs mn pour faire review sur ce PR ? J'ai révisé et cela me semble OK mais je n'ai pas le bagage technique pour réviser et identifier des éventuelles coquilles. 

Merci !

2022-11-14 15:50 UTC, majouda requested changes

2022-11-14 15:50 UTC, majouda commented on so_available_qty_popover_alternative/README.rst
> +.. image:: static/description/sale_order.png
Hello @abenzbiria 

Il manque le dossier static dans ce PR, tu as oublié le l'ajouter avec Git Add je crois.

2022-11-14 15:50 UTC, majouda commented on so_available_qty_popover_alternative/models/sale_order_line.py
> +                    line.product_id.qty_available >=  line.product_uom_qty:
Ici il faut garder le with_context(company_owned=True) pour chercher la qty_available

2022-11-14 15:50 UTC, majouda commented on so_available_qty_popover_alternative/models/product_product.py
> +            for child_id in child_locations_ids :
Avec un seul niveau de child_ids de l'emplacement parent on ne couvre pas toutes les quantités en stock, il faut descendre jusqu'au dernier child avec une fonction récursive.

2022-11-14 15:50 UTC, majouda commented on so_available_qty_popover_alternative/models/product_product.py
> +    def get_warehouse_qty(self, warehouse_id):
Voir si on peut juste utiliser le champs stock_quant_ids filtrer par les emplacements du warehouse du SO au lieu de faire une méthode qui cherche les quantités en stock.

2022-11-14 16:28 UTC, abenzbiria commented on so_available_qty_popover_alternative/models/product_product.py
> +    def get_warehouse_qty(self, warehouse_id):
Justement la separation par warehouse dans les domains n'existe pas
le calcul  qty_available utilise  les domains puis il passe par les quants
C'est plus performant de filtrer  par warehouse.
A suivre

2022-11-14 16:28 UTC, abenzbiria commented on so_available_qty_popover_alternative/models/product_product.py
> +            for child_id in child_locations_ids :
Bien vu .
En principe le  niveau 0 d'une location interne récupére tous les sous emplacements
A vérifeir

2022-11-14 16:56 UTC, abenzbiria commented on so_available_qty_popover_alternative/README.rst
> +.. image:: static/description/sale_order.png
Non je l'ai pas encore ajouter , j'attends qu'on teste puis j'ajoute ce qu'il faut pour le readme et le makup ;).

2022-11-14 16:58 UTC, abenzbiria commented on so_available_qty_popover_alternative/models/sale_order_line.py
> +                    line.product_id.qty_available >=  line.product_uom_qty:
Il y a cette fonction pour filterer par warehouse  _get_domain_locations.
Je vais tester si ça marche je fais un nouveau commit

2022-11-14 17:12 UTC, abenzbiria commented on so_available_qty_popover_alternative/models/sale_order_line.py
> +                    line.product_id.qty_available >=  line.product_uom_qty:
ça  marche avec  un  **with_context(warehouse=self.order_id.warehouse_id.id).qty_available**
Merci

2022-11-18 14:34 UTC, jjbreard2 approved these changes

2022-11-18 16:22 UTC, merged

2022-11-18 16:23 UTC, qtiplb commented
@majouda J'ai mergé puisque tous les changements demandés étaient resolve, mais si tu peux jeter tout de même un dernier coup d'oeil merci!